name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
          # cache: 'npm'

      - run: npm ci
        working-directory: ${{ env.working-directory }}

      - run: npm run lint
        working-directory: ${{ env.working-directory }}

      - run: npm run build --if-present
        working-directory: ${{ env.working-directory }}
